#!/bin/sh
num1="$1"
num2="$2"
[ "$3" = "-q" ] && quiet=1
decnum=0
unset sumfrac
for num in "$num1" "$num2"; do
  case "$num" in
    *"."*) : $((decnum+=1)) ;;
  esac
done
[ "$decnum" -eq 0 ] && {
  [ "$quiet" ] || printf '  %s\n+ %s\n----\n' "$num1" "$num2"
}
if [ "$decnum" -ge 1 ]; then
# add decimals
  [ "$(printf '%.1s' "$num1")" = "-" ] && carryneg1="-"
  [ "$(printf '%.1s' "$num2")" = "-" ] && carryneg2="-"
  [ "$carryneg1" ] && unset sumfrac
  [ "$carryneg2" ] && unset sumfrac
  whole1="${num1%%.*}"
  frac1="${carryneg1}${num1##*.}"
  whole2="${num2%%.*}"
  frac2="${carryneg2}${num2##*.}"
  # the currect number of 0s needs to be injected to match with other
  frac1="$(zeroadd "$frac1" "$frac2")"
  frac2="$(zeroadd "$frac2" "$frac1")"
  # it may be possible to skip some steps if we check which numbers actually contain fractional parts
  # however until the logic of fraction math works 100% of the time its better to force it and possibly have a bug that can then be fixed
  ##
  # a + (-b) = -b + a
  ##
  [ "$carryneg1" ] && {
    oldfrac1="$frac1"; oldfrac2="$frac2"
    oldwhole1="$whole1"; oldwhole2="$whole2" 
    frac1="$oldfrac2"; whole1="$oldwhole2"
    frac2="$oldfrac1"; whole2="$oldwhole1"
    # this should in theory make num1, num2 and num2, num1
    unset carryneg1 oldwhole1 oldwhole2 oldfrac1 oldfrac2
  }
  ##
  # working with - on the lower side is better for fractional
  ##
  # the opossing is true for wholes I believe

  [ "$quiet" ] || printf '  %s\n+ %s\n----\n' "${carryneg2:+ }$whole1${frac1:+.${frac1#-}}" "${carryneg1:+ }$whole2${frac2:+.${frac2#-}}"
  if [ "$sumfrac" ]; then
    [ "$sumfrac" = "$num1" ] && sumfrac="$frac1"
    [ "$sumfrac" = "$num2" ] && sumfrac="$frac2"
    [ "$quiet" ] || echo "skip | $sumfrac"
  elif [ "$decnum" -gt 0 ]; then
    #echo fracadd
  # if the sum was declared above then it's possible to skip the decimal addition as we're only adding 0
    frac1="$(zeroadd ${frac1#-} ${frac2#-})"
    frac2="$(zeroadd ${frac2#-} ${frac2#-})" 
    # zeroadd() checks for length automatically
    # returning the original if greater than or equal to $2 
    # thus we can simply call it to check
    unset sumfrac fracnext1 fracnext2 fracwholecurrent1 fraccurrent2 fracadd1 fracadd2 stored_frac1 stored_frac2 stored_borrow __new_frac1 __new_frac2 _frac_lookahead1 _frac_lookahead2
    #echo "$frac1 | $frac2 -- $whole1 | $whole2"
    digit=0; while [ "${frac1}" ] && [ "${frac2}" ]; do
      [ "$quiet" ] || printf '%s\n----\n' "Step $((digit+1))"  
      fracnext1="${frac1%?}"; fraccurrent1="${frac1#$fracnext1}"
      fracnext2="${frac2%?}"; fraccurrent2="${frac2#$fracnext2}"
      ## char loop setup; stupid sh bs
      fracadd1="${carryneg1}$fraccurrent1"
      fracadd2="${carryneg2}$fraccurrent2"
      # ^ this is done as issues appear when done inside $(()) if one is unset
      if [ "$fraccurrent1" != "-" ] && [ "$fraccurrent2" != "-" ]; then
        [ "$quiet" ] || printf '  %s\n+ %s\n----\n' "${carryneg2:+ }$fracadd1" "${carryneg1:+ }$fracadd2"
        # echo "$carryneg1 -- $carryneg2 | $fracnext1 -- $fracnext2"
        ##
        # negative issue:
        # borrows need to occur if current digit of #2/#1 is < 0 and digit of oppossing number is < flipped other digit
        # the logic for this is actually super annoying
        ##
        # see https://social.translunar.academy/notice/AqLEjpHSMhX50lrUtk
        # as well as previous commits for logic
        ##
        presum="$((fracadd1 + fracadd2))"
        sumfrac="${presum}${sumfrac#-}"
        #echo "----"
        [ "$quiet" ] || echo "| sum = $sumfrac"
      fi
      ##
      frac1="$fracnext1"
      frac2="$fracnext2"
      : $((digit+=1))
    done
    sumfrac="${sumfrac#-}"
  fi
fi
[ "$whole1" ] || whole1="${num1%%.*}"
[ "$whole2" ] || whole2="${num2%%.*}"
[ "$(printf '%.1s' "$num1")" = "-" ] && carryneg1="-"
[ "$(printf '%.1s' "$num2")" = "-" ] && carryneg2="-"
# %%.* evals to no change if not present
unset sumwhole wholenext1 wholenext2 wholecurrent1 wholecurrent2 wholeadd1 wholeadd2 digit
digit=0; while [ "${whole1}" ] && [ "${whole2}" ]; do
  [ "$quiet" ] || printf '%s\n----\n' "Whole step $((digit+1))"
  wholenext1="${whole1%?}"; wholecurrent1="${whole1#$wholenext1}"
  wholenext2="${whole2%?}"; wholecurrent2="${whole2#$wholenext2}"
      ## char loop setup; stupid sh bs
      wholeadd1="${carryneg1}$wholecurrent1"
      wholeadd2="${carryneg2}$wholecurrent2"
      # ^ this is done as issues appear when done inside $(()) if one is unset
  if [ "$wholecurrent1" != "-" ] && [ "$wholecurrent2" != "-" ]; then
    [ "$quiet" ] ||printf '  %s\n+ %s\n----\n' "$wholeadd1" "$wholeadd2"
    sumwhole="$(( wholeadd1 + wholeadd2 ))${sumwhole}"
  fi
  ##
  whole1="$wholenext1"
  whole2="$wholenext2"
  : $((digit+=1))
done
sumfrac="${sumfrac#-}"
[ "$quiet" ] || printf '  %s\n+ %s\n---\n' "${sumwhole}.00" "00.${sumfrac:-0}"
echo "$sumwhole.${sumfrac:-0}"

# TODO: carryneg overflows
# if result length is > 1 then it overflowed the single digit

# TODO: solve issue with negatives
# -20 + 5 = -15
# returns 

# TODO: 0 + -0.5 = -0.5
# 0 + -0 = 0
# thus expected method does not work